class Commands:
    LEECH = "leechwb"
    PURGE = "purgewb"
    PAUSEALL = "pauseallwb"
    RESUMEALL = "resumeallwb"
    STATUS = "statuswb"
    SETTINGS = "settingswb"
    EXEC = "execwb"
    UPLOAD = "uploadwb"
    YTDL = "ytdlwb"
    PYTDL = "pytdlwb"
    ABOUT = "aboutwb"
    GETLOGS = "getlogswb"
    SERVER = "serverwb"
    USERSETTINGS = "usettingwb"
    INSTADL = "instadlwb"
    START = "startwb"
    USTATUS = "ustatuswb"
