class Commands:
    LEECH = "leechfr"
    PURGE = "purgefr"
    PAUSEALL = "pauseallfr"
    RESUMEALL = "resumeallfr"
    STATUS = "statusfr"
    SETTINGS = "settingsfr"
    EXEC = "execfr"
    UPLOAD = "uploadfr"
    YTDL = "ytdlfr"
    PYTDL = "pytdlfr"
    ABOUT = "aboutfr"
    GETLOGS = "getlogsfr"
    SERVER = "serverfr"
    USERSETTINGS = "usettingfr"
    INSTADL = "instadlfr"
    START = "startfr"
    USTATUS = "ustatusfr"
